function out = readSTO(motFile)
% This function takes the .sto file generated by OpenSim when calculating
% inverse kinematics, usually named "_ik_model_marker_locations.sto", or a
% .sto file generated from inverse dynamics, and turns it into a table
% containing the same information. The resulting table will be identical in
% format to a table generated by readTRC(). The original .sto file contains
% the marker position over time of the model fit by inverse kinematics. 
% [stoTable] = readSTO(stoFile);
% 
% Returns: 
% stoTable - A table where each column is Header, a marker coordinate 
% (e.g. R_ASIS_x), or a joint moment, and each row is a different time. 

    assert(ischar(motFile) && endsWith(lower(motFile), '.sto'), 'This is not a MOT file (*.mot).');

    data = importdata(motFile);

    if iscell(data)
        data = importdata(motFile, ' ');
    end
    out = array2table(data.data);
    
    if isfield(data, 'colheaders')
        headers = data.colheaders;
    else
        headers = split(data.textdata{end, :});
    end
    headers(cellfun('isempty', headers)) = [];
    headers = strrep(headers, '/', '_');
    headers = strrep(headers, '.', '_');
    headers = strrep(headers, '\', '_');
    headers = genvarname(headers);
    
    headers{1}='Header';
    out.Properties.VariableNames = headers;
end
